#!/bin/bash
#
# Build a local wheelhouse with everything needed to install sasview
#
# This wheelhouse can be passed to the flatpak builder to provide all the
# packages needed inside the flatpak.
#
# Copyright (c) 2025 SasView Developers
#
# Released under the same licence as SasView.

# TODO:
# - can the git refs be obtained from the workflow?
# - what would the URLs look like for unreleased artifacts?


set -euo pipefail

set -x

VER=6.1.1
GITREF=refs/tags/v$VER
REQ_URL="https://raw.githubusercontent.com/SasView/sasview/$GITREF/build_tools/requirements-release-ubuntu-latest.txt"
# For future releases, the remote filename will hopefully change
WHEEL_URL="https://github.com/SasView/sasview/releases/download/v$VER/Sasview-$VER.whl"

download() {
  local F=$1 U=$2
  echo -n "... $F"
  if [ ! -f $F ]; then
    wget -q -O $F $U
  else
    echo "(cached)"
  fi
}

# run a command in the flatpak environment to use its tools (such as the Python version)
# quoting is, of course, painful - the command needs to be
# a single argument to this function
fp_run() {
  flatpak run \
    --share=network \
    --filesystem="$PWD" \
    --command=bash org.kde.Sdk//6.9 -c \
    "$1"
}

WHEELHOUSE="wheels"
PYVER=$(fp_run "python -c \"import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')\"")
WHEELHOUSE_ARCHIVE=wheelhouse-sasview-flatpak-py$PYVER-sasview$VER.tar.gz
REQ="requirements.txt"
SASVIEW_WHEEL=sasview-$VER-py3-none-any.whl


mkdir -p "$WHEELHOUSE"


echo -e "Fetching sasview resources"
download $REQ $REQ_URL
download $WHEELHOUSE/$SASVIEW_WHEEL $WHEEL_URL
# include additional things like sasmodels and sasdata here?

echo -e "\n\n\nDownloading wheels"
fp_run "python -m pip download -r $PWD/$REQ -d /$PWD/$WHEELHOUSE"

echo -e "\n\n\nVerifying wheels"
fp_run "python -m pip download -r $PWD/$REQ -d /$PWD/$WHEELHOUSE"

echo -e"\n\nCreating archive $WHEELHOUSE_ARCHIVE"
tar zcf "$WHEELHOUSE_ARCHIVE" "$WHEELHOUSE"
