#!/bin/bash
#
# Build a local wheelhouse with everything needed to install sasview
#
# This wheelhouse can be passed to the flatpak builder to provide all the
# packages needed inside the flatpak.
#
# Copyright (c) 2025 SasView Developers
#
# Released under the same licence as SasView.

# TODO:
# - can this be run by the runtime Python itself?
# - can the Python version and git refs be obtained from the workflow?

set -euo pipefail

PYVER=3.12
VER=6.1.1
WHEELHOUSE="wheels"
WHEELHOUSE_ARCHIVE=wheelhouse-sasview-flatpak-py$PYVER-sasview$VER.tar.gz
GITREF=refs/tags/v$VER

REQ_URL="https://raw.githubusercontent.com/SasView/sasview/$GITREF/build_tools/requirements-release-ubuntu-latest.txt"
REQ="requirements.txt"

WHEEL_URL="https://github.com/SasView/sasview/releases/download/v6.1.1/Sasview-6.1.1.whl"
WHEEL=sasview-$VER-py3-none-any.whl

if [ $(python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')") != $PYVER ]; then
  echo "ERROR: python version must match inside the runtime"
  exit 1
fi


mkdir -p "$WHEELHOUSE"

echo -e "Fetching sasview data"
wget -q -O $REQ $REQ_URL
wget -q -O $WHEELHOUSE/$WHEEL $WHEEL_URL


echo -e "\n\n\nDownloading wheels"
python -m pip download -r "$REQ" -d "$WHEELHOUSE"

echo -e "\n\n\nVerifying wheels"
python -m pip install --no-index --find-links="$WHEELHOUSE" -r "$REQ" "$WHEELHOUSE/$WHEEL" --dry-run

echo -e"\n\nCreating archive $WHEELHOUSE_ARCHIVE"

tar zcf "$WHEELHOUSE_ARCHIVE" "$WHEELHOUSE"
